name: deployment_workflow
on: 
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - dev
  workflow_dispatch: 
  push:
    branches:
      - dev
jobs:
  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
      - name: Set up Node.js
        run: npm ci
      - name: lint
        run: npm run lint
  tests_job:
    needs: lint_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
      - name: Set up Node.js
        run: npm ci
      - name: Test
        run: npm run test
      - name: gather artifacts  
        uses: actions/upload-artifact@v4
        with: 
          name: dist-file 
          path: |
            dist
            package.json
  deployment_job:
    needs: tests_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
      - name: Set up Node.js
        run: npm ci
      - name: Build
        run: npm run build 
      - name: Deploy   
        run: echo "Deploying the application..."
